name: Deploy ECS Application

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: backend-repo
  ECS_SERVICE: backend-service
  ECS_CLUSTER: ecs-cluster
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: backend-app

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::886492071931:role/github-actions-role
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY ./backend
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition backend-task \
            --query taskDefinition > task-definition.json

      - name: Fill New Image ID
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: backend-app
          image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: backend-service
          cluster: ecs-cluster
          wait-for-service-stability: true
